---
title: "DSC for evaluating linear regression methods"
author: "Peter Carbonetto, Gao Wang and Matthew Stephens"
date: April 9, 2019
site: workflowr::wflow_site
output: workflowr::wflow_html
---

This repository implements a [Dynamic Statistical Comparison][dsc]
(DSC) to evaluate prediction accuracy of linear regression methods
in different scenarios.

Follow the links below for an overview of the results, and for
instructions on how to run the DSC on your own computer.

+ [Usage instructions.](usage_instructions.html)

+ [Comparison of linear regression methods in the four scenarios from
  Zou & Hastie (2005).](results_overview.html)

## License

Copyright (c) 2018-2019, Gao Wang, Peter Carbonetto and Matthew
Stephens.

All source code and software in this repository are made available
under the terms of the [MIT license][mit-license].

## Contributors

This repository was developed by [Gao Wang][gao], [Peter
Carbonetto][peter] and [Matthew Stephens][matthew] at the University
of Chicago.

[dsc]: https://github.com/stephenslab/dsc
[gao]: https://github.com/gaow
[peter]: http://pcarbo.github.io
[matthew]: https://stephenslab.uchicago.edu
[mit-license]: https://opensource.org/licenses/mit-license.html
